default l0
menu title U-Boot menu
prompt 1
timeout 30

label l0
    menu label 6.8.2-edge-rockchip-rk3588
    linux /vmlinuz-6.8.2-edge-rockchip-rk3588
    initrd /initrd.img-6.8.2-edge-rockchip-rk3588
    fdtdir /dtbs/6.8.2-edge-rockchip-rk3588/
    append root=UUID=2c8037be-439b-4432-8453-deb802a5b964 rootfstype=xfs quiet splash rw earlycon console=tty1 console=ttyS2,1500000n8 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 panic=10 net.ifnames=0

label l1
    menu label 6.8.2-edge-rockchip-rk3588 Recovery
    linux /vmlinuz-6.8.2-edge-rockchip-rk3588
    initrd /initrd.img-6.8.2-edge-rockchip-rk3588
    fdtdir /dtbs/6.8.2-edge-rockchip-rk3588/
    append root=UUID=2c8037be-439b-4432-8453-deb802a5b964 rootfstype=xfs quiet splash rw single earlycon console=tty1 console=ttyS2,1500000n8 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 panic=10 net.ifnames=0
